from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Literal

from pydantic import BaseModel, Field


class Trigger(BaseModel):
    """
    Defines a condition that triggers the Circuit Breaker.
    """

    metric_name: str = Field(..., description="The name of the metric to monitor (e.g., 'error_rate').")
    threshold: float = Field(..., description="The value threshold that triggers the breaker.")
    window_seconds: int = Field(
        ..., gt=0, description="The time window in seconds to evaluate the metric. Must be positive."
    )
    operator: Literal[">", "<"] = Field(
        ">", description="Comparison operator. Default is '>' (greater than threshold)."
    )
    aggregation_method: Literal["SUM", "AVG", "COUNT", "MIN", "MAX"] = Field(
        "SUM", description="Aggregation method for the metric over the window. Default is SUM."
    )


class SentinelConfig(BaseModel):
    """
    Configuration for the Sentinel monitor.
    """

    agent_id: str = Field(..., description="Unique identifier for the agent being monitored.")
    sample_rate: float = Field(
        0.01, ge=0.0, le=1.0, description="Fraction of traffic to sample (0.0 to 1.0). Default 1%."
    )
    drift_threshold_kl: float = Field(0.5, ge=0.0, description="KL Divergence threshold for output drift detection.")
    circuit_breaker_triggers: List[Trigger] = Field(
        default_factory=list, description="List of triggers that can trip the circuit breaker."
    )
    notification_channels: List[str] = Field(
        default_factory=list, description="List of email addresses or channels for notifications."
    )


class AlertSeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class Alert(BaseModel):
    """
    Represents an alert generated by the system.
    """

    message: str = Field(..., description="Human-readable alert message.")
    severity: AlertSeverity = Field(..., description="Severity level of the alert.")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc), description="Time when the alert was generated."
    )


class HealthReport(BaseModel):
    """
    A snapshot of the agent's health.
    """

    timestamp: datetime = Field(..., description="Time of the report.")
    agent_status: Literal["HEALTHY", "DEGRADED", "CRITICAL"] = Field(..., description="Current status of the agent.")
    metrics: Dict[str, Any] = Field(
        default_factory=dict,
        description="Key-value pairs of current metrics (e.g., avg_latency, live_faithfulness_score).",
    )
    active_alerts: List[Alert] = Field(default_factory=list, description="List of currently active alerts.")
